# -*- coding: utf-8 -*-
"""AreaCircle36.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TyfMPd1p7MNDF8NruYNMhxwl5rLlxCmk
"""

# Вычисление площади круга по его радиусу
pi, radius = 3.1415926, 36
print(round(((radius **2) * pi), 4))