# -*- coding: utf-8 -*-
"""Operations_with_variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QYz508fnWN0_0MV1IbCvEC2xQL__q4HB
"""

# переменные
num = 3 + 5
num2 = num + 2
num = num2 * 2
#print(num, num2)
num = num2 / 33
#print(num, num2)

x, y, z = 1, 2, 3
(x / y ** z) * z + (z * z / y)
x, y, z
type(x), type(y), type(z)

isinstance(z, bool)

id(num), id(x), id(y), id(z)
int(num2)
float(num2)
float((3 + x * y ** z) * z + (z * z / y))
int((3 + x * y ** z) * z + (z * z / y))

логический = bool
#print(логический)