# -*- coding: utf-8 -*-
"""Operations on_the_boolean_data_type.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/165qxP4X-XAjARpf5das_2rigrmZgAAzm
"""

True, False
True + True + True
bool(0)
bool(1)
bool(10)

#x = None
#print(x)

True and bool(1)
2 == 2 and 2 < 3
2 == 2 and 2 > 3
2 == 3 and 2 / 0 > 3
2 == 2 and 10 / 1 > 3

True or False
1 == 1 or False
1 == 3 or 2 < 10
1 == 5 or 5 > 6

not False
not True