# -*- coding: utf-8 -*-
"""String_Operations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tolKoeAWROhOqVAqiBZRYjRuLkG4WciO
"""

txt = 'Hello World!'
#print("Hello\nWorld!")
#print(txt)
len(txt)
txt * 5
txt + ' +1'
txt[-5:-4]
l = len(txt)
#print(l//2)
str(l//2)
txt.find('o'), txt.find('o'), txt.find('o')
#txt.find('6')
#txt.replace(' ','')
#print(txt)

txt.split('o')