# -*- coding: utf-8 -*-
"""Task_2_4_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OQUPXMDUon_e7XUPVs2-QTpTvOJ6m2B9
"""

from os import lstat
# Задача 2.4.

# Пункт A.
# Напишите функцию, которая удаляет все восклицательные знаки из заданной строк.
# Например,
# foo("Hi! Hello!") -> "Hi Hello"
# foo("") -> ""
# foo("Oh, no!!!") -> "Oh, no"

def remove_exclamation_marks(s):    
    rStr = s.replace('!','')
    return rStr
print(remove_exclamation_marks("Oh!!!!!!!, no!!!"))

# Пункт B.
# Удалите восклицательный знак из конца строки. 
# remove("Hi!") == "Hi"
# remove("Hi!!!") == "Hi!!"
# remove("!Hi") == "!Hi"

def remove_last_em(s):
    pos2 = s.rfind('!')
    l = len(s) - pos2
    if l == 1:
        rStrLast = s[:-1]
    else:
        rStrLast = s
    return rStrLast
#    pass
print(remove_last_em("!!!Hi!!!"))

# Дополнительно

# Пункт С.
# Удалите слова из предложения, если они содержат ровно один восклицательный знак.
# Слова разделены одним пробелом.
# Например,
# remove("Hi!") === ""
# remove("Hi! Hi!") === ""
# remove("Hi! Hi! Hi!") === ""
# remove("Hi Hi! Hi!") === "Hi"
# remove("Hi! !Hi Hi!") === ""
# remove("Hi! Hi!! Hi!") === "Hi!!"
# remove("Hi! !Hi! Hi!") === "!Hi!"
#s = "!Hi Hi !Hi! Hi! Hi! !Ht"

def remove_word_with_one_em(s):
    edttxt = ''
    lst = s.split(' ')
    for i in lst:
        pos1 = i.find('!')
        pos2 = i.rfind('!')
        if 0 > pos1:
            edttxt = edttxt + ' ' + i
        elif pos1 != pos2:
            edttxt = edttxt + ' ' + i
    edttxt = edttxt
    pos1 = edttxt.find(' ')
    if pos1 == 0:
        edttxt = edttxt[1:]
    return edttxt 

print(remove_word_with_one_em("Hi !Hi Hi !Hi! !Hi Hi Hi! Hi! !Ht !!H!!"))

