# -*- coding: utf-8 -*-
"""Task_1_2_bcd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LTHZnyXWgX0sRebYqS4C5h3jvqlMyt27
"""

# Пункт B. 
# Есть словарь песен 
# Распечатайте общее время звучания трех случайных песен
# Вывод: Три песни звучат ХХХ минут.

my_favorite_songs_dict = {
    'Waste a Moment': 3.03,
    'New Salvation': 4.02,
    'Staying\' Alive': 3.40,
    'Out of Touch': 3.03,
    'A Sorta Fairytale': 5.28,
    'Easy': 4.15,
    'Beautiful Day': 4.04,
    'Nowhere to Run': 2.58,
    'In This World': 4.02,
}

import random
t1 = 0
for i in range(3):
    for i in my_favorite_songs_dict:
        lst = [i for i in my_favorite_songs_dict]
    x = random.randint(0, len(my_favorite_songs_dict)-1)
    key1 = lst[x]
    t1 = t1 + my_favorite_songs_dict.get(key1,0)

print('Три песни звучат', t1, 'минут')
# Дополнительно для пунктов A и B
# Пункт C.
# Сгенерируйте случайные песни с помощью модуля random

# В пунктах A и B уже сгенерированы случайные песни по условиям.

# import random

# Дополнительно 
# Пункт D.
# Переведите минуты и секунды в формат времени. Используйте модуль datetime
import datetime
# В Colab нет метода strptime. Сделаю по своему.
seconds = ''
minutes = str(int(t1))
seconds = str(int((t1 % 1) * 60))
if (round((t1 % 1) * 60)) < 10:
    seconds = '0' + seconds
t2 = minutes + ':' + seconds
print('Три песни звучат', t2, 'минут:секунд')