# -*- coding: utf-8 -*-
"""Task_2_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P3sbGobx_92qZueFbu_W_9V7Vkj7cFqq
"""

# Задача 2.1. 
# Создайте две функции maximum и minimum,
# которые получают список целых чисел в качестве входных данных 
# и возвращают наибольшее и наименьшее число в этом списке соответственно.
# Например,
# * [4,6,2,1,9,63,-134,566]         -> max = 566, min = -134
# * [-52, 56, 30, 29, -54, 0, -110] -> min = -110, max = 56
# * [42, 54, 65, 87, 0]             -> min = 0, max = 87
# * [5]                             -> min = 5, max = 5
# функции sorted, max и min использовать нельзя!

arr1 = [4,6,2,1,9,63,-134,566]
arr2 = [-52, 56, 30, 29, -54, 0, -110]
arr3 = [42, 54, 65, 87, 0]
arr4 = [5]

def minimum(arr):
    minarr = arr[0]
    for i in range(len(arr)):
        if arr[i] <= minarr:
            minarr = arr[i]
    minarrtxt = 'min = ' + str(minarr)
    return minarrtxt
    #pass

def maximum(arr):
    maxarr = arr[0]
    for i in range(len(arr)):
        if arr[i] >= maxarr:
            maxarr = arr[i]
    maxarrtxt = 'max = ' + str(maxarr)
    return maxarrtxt
    #pass

print(arr1)
print(minimum(arr1), maximum(arr1))

print(arr2)
print(minimum(arr2), maximum(arr2))

print(arr3)
print(minimum(arr3), maximum(arr3))

print(arr4)
print(minimum(arr4), maximum(arr4))

